version: "3"
networks:
  loki:

services:
  loki:
    container_name: loki
    image: grafana/loki:1.5.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yaml
    networks:
      - loki
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
  promtail:
    image: grafana/promtail:1.5.0
    restart: always
    volumes:
      - /var/log:/var/log
      - promtail-config:/etc/promtail
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - loki