server:
  http_listen_port: 9080
  grpc_listen_port: 0

# Positions
positions:
  filename: /data/loki/positions.yaml
  sync_period: 10s #10秒钟同步一次

# Loki服务器的地址
clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push
  batchwait: 10s

scrape_configs:
  - job_name: go-use
    static_configs:
      - targets:
          - localhost
        labels:
          job: accesslog
          __path__: /data/logs/*.log    # 日志目录



          server:
  http_listen_port: 9080
  grpc_listen_port: 0


