@baseUrl = http://192.168.1.163:8081

###
GET  {{baseUrl}}/api/health


###gorm
GET  {{baseUrl}}/api/staff


###redis
GET {{baseUrl}}/api/redis/test


###token
GET {{baseUrl}}/api/token/test


###token
GET {{baseUrl}}/api/v1/ipfs/get_data?cid=QmQ4Pvi4HMMXPRT9c6Nsys213LdckW7MbEYwjL6wEVewPo