
#线上环境
[hashids]
  length = 12
  secret = "6ab6122836cfef95f8db"

[jwt]
  expireduration = 24
  secret = "i1ydX9RtHyuJTrw7frcu"

[mail]
  host = "smtp.163.com"
  pass = ""
  port = 465
  to = ""
  user = ""

[pg]

  [pg.base]
    connmaxlifetime = 60
    maxidleconn = 60
    maxopenconn = 10

  [pg.read]
    host = "192.168.1.5"
    port = "5434"
    name = "xicheng"
    pass = "pass_2020"
    user = "xicheng"

  [pg.write]
    host = "192.168.1.5"
    port = "5434"
    name = "xicheng"
    pass = "pass_2020"
    user = "xicheng"

[redis]
  addr = "192.168.1.6:6379"
  db = "10"
  maxretries = 3
  minidleconns = 5
  pass = "redis_pass_2020"
  poolsize = 10

[urltoken]
  expireduration = 10
  secret = "i1ydX9RtHyuJTrw7frcu"
