definitions:
  response.Resp:
    properties:
      code:
        type: string
      data:
        type: object
      msg:
        type: string
    type: object
host: 192.168.1.163:8081
info:
  contact: {}
  license:
    name: MIT
    url: https://www.baidu.com
  title: swagger 接口文档
  version: "2.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: 服务是否启动正常检查
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 健康检查接口
      tags:
      - 监测服务
  /v1/ipfs/novel/get:
    get:
      consumes:
      - application/json
      description: 小说dapp小说文本数据
      parameters:
      - description: string valid
        in: query
        name: cid
        type: string
      - description: int valid
        in: query
        name: num
        type: integer
      - description: int valid
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Resp'
      summary: 根据hash下载ipfs数据
      tags:
      - 小说
  /v1/ipfs/novel/upload:
    post:
      consumes:
      - application/json
      description: 上传小说文本章节,文本类型txt等上传成功返回文本hash 并且需要记录一下数据到pg 小说标题,图片,作者,上传到ipfs的hash。
      parameters:
      - description: string valid
        in: query
        maxLength: 10
        minLength: 5
        name: string
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Resp'
      summary: 上传ipfs数据
      tags:
      - 小说
swagger: "2.0"
